query DeviceQuery($name: String!) {
  NetworkDevice(name__value: $name) {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        description {
          value
        }
      }
    }
  }
}