# yaml-language-server: $schema=https://schema.infrahub.app/python-sdk/repository-config/latest.json
---
artifact_definitions:
  - name: "device_configuration"
    artifact_name: "Device configuration file"
    parameters:
      name: "name__value"
    content_type: "text/plain"
    targets: "DeviceGroup"
    transformation: "device_config_transform"
  - name: "device_configuration_json"
    artifact_name: "Device configuration JSON"
    parameters:
      name: "name__value"
    content_type: "application/json"
    targets: "DeviceGroup"
    transformation: "device_config_json"

check_definitions:
  - name: "check_color_tags_name"
    class_name: "ColorTagsCheck"
    file_path: "checks/tags_check/tags_check.py"
    targets: "ColorTags"
    parameters:
      tag_name: "name__value"

jinja2_transforms:
  - name: device_config_transform # Unique name for your transform
    description: "device config transform" # (optional)
    query: "device_config_query" # Name or ID of the GraphQLQuery
    template_path: "templates/device_config.j2"

python_transforms:
  - name: device_config_json
    class_name: DeviceConfigTransform
    convert_query_response: true
    file_path: "device_config_render/device_config.py"

queries:
  - name: device_config_query
    file_path: "device_config_render/device_config.gql"
  - name: tags_check
    file_path: "checks/tags_check/tags_check.gql"

schemas:
  - schemas/dcim.yml

objects:
  - data/00-tags.yml
  - data/05-dcim.yml
