# yaml-language-server: $schema=https://schema.infrahub.app/python-sdk/repository-config/latest.json
---
check_definitions:
  - name: "check_color_tags_name"
    class_name: "ColorTagsCheck"
    file_path: "checks/tags_check/tags_check.py"
    targets: "ColorTags"
    parameters:
      name: "name__value"

# python_transforms:
#   - name: device_config_transform
#     class_name: DeviceConfigTransform
#     convert_query_response: true
#     file_path: "device_config_render/device_config.py"

queries:
  # - name: device_config_query
  #   file_path: "device_config_render/device_config.gql"
  - name: tags_check
    file_path: "checks/tags_check/tags_check.gql"
